### ISSUE TITLE
Mega File (Unknown) not downloading 

### ISSUE THREAD

**Issue by dcbang747** [TitansBane/Elysium-Remastered#10]
A file with the link "https://mega.nz/file/ccNCxbqA#zcsaLy1Yb3KhX_9UHv1feLkQqrzJGZARxTzATWBmNA4"
seems to no longer exist. Can someone help, please. Thanks

**Comment by dcbang747** [comment]
After some cursory research, it is the CORE FILES of Elysium remastered not downloading

**Comment by TheClock69** [comment]
Heya,

I know, I got the proper download file on the suppirt page, found on the Wabbajack discord. But the thing that fixed it all, for me. Was to delete everything (skyrim AE, folders inc. and all of the downloaded mods). Just start fresh, and try again. Download CC content. 
You got this,
And the game is so worth it! 

Good luck!
