### ISSUE TITLE
Main menu crash

### ISSUE THREAD

**Issue by MotDIITheGreat** [TitansBane/Elysium-Remastered#11]
I've downloaded and installed modlist step-by-step following readme, but after loading main menu game just crashes without any issue message. 
RTX 2070,
AMD Ryzen 5 3600 6-Core Processor 3.59 GHz,
16 GB of RAM,
pagefile ~ 40GB

**Comment by TheClock69** [comment]
Savage.

I have seen suggestions to work around similar issues. I have just forgotten them, over time. 
I can suggest the Wabbajack discord service, for a fast tailored response.
Wabbajack discord -> Elysium Remastered Support (page)

All the best, and good luck!

J/TheClock69
