### ISSUE TITLE
Modpack not on Wabbajack

### ISSUE THREAD

**Issue by Salmonse** [TitansBane/Elysium-Remastered#13]
I went to install the pack after buying skyrim legendary edition, and I can't find it in the wabbajack modlist page. I noticed that there is an update page that v1.3.0 is unreleased as of right now, is this related?

**Comment by TheClock69** [comment]
It is supposed to be skyrim anniversary edition.

Uhm... I wonder if it is currently under maintenance, or something... else. 🤔

Good luck!
