### ISSUE TITLE
Wabbjack Install Of Elysium Giving error

### ISSUE THREAD

**Issue by jgore077** [TitansBane/Elysium-Remastered#139]
Im getting this error after upgrading to the AE version

```
00:36:56.996 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Data_Scripts.zip (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.1130.0|data\scripts.zip)
```

I was getting more errors about missing bsa files but now its just this single error

**Comment by santiagofavrin** [comment]
@jgore077 Hey, I see you marked this as completed, did you find a solution? I'm facing the same issue.

**Comment by jgore077** [comment]
Yes I had to install the creation club through steam and after that the error was gone

**Comment by santiagofavrin** [comment]
For whoever else may read this: I needed the anniversary edition DLC, had just SE installed
