### ISSUE TITLE
 no Elysium Remastered in "Browsing Modlist"

### ISSUE THREAD

**Issue by delmoore** [TitansBane/Elysium-Remastered#14]
There is no Elysium Remastered in Browsing Modlist. I choosed the Game Skyrim Special Edition and also searched for "Elysium".

Other Quesion:
Is there the option of german subtitle?

**Comment by notyateart** [comment]
You can manually download the file in the releases section and then select "install from disk" in wabbajack.

**Comment by delmoore** [comment]
Thank you its running but faced directly an error, mentioned in the newest reported Issue.
Is there an option for german subtitle ?

**Comment by notyateart** [comment]
Yes, we have to wait until it's fixed.

I don't know if there are subtitles but I am guessing that if there was support you'd have to install it yourself and it's not included.
