### ISSUE TITLE
Not being able to download and continue installation

### ISSUE THREAD

**Issue by Josemanit132** [TitansBane/Elysium-Remastered#24]
Hello! My wabbajack is not being able to download these 3 mods and so it doesn't let me continue :(
Thanks!

-High_Poly_Head_v1.4_(SE).zip
-Remastered Ash Piles Of Skyrim-44971-1-1-1611883469.7z
-OBIS SE - Headhunter - patch-52520-1-05-1648483442.zip

Downloading OBIS SE - Headhunter - patch-52520-1-05-1648483442.zip
34.2 - Downloading High_Poly_Head_v1.4_(SE).zip
34.2 - Downloading Remastered Ash Piles Of Skyrim-44971-1-1-1611883469.7z
34.27 - File hash check (-42) 4f04c55d2bc0afe4ccb523a180fb8d508b120d370b1aee66a8e80c6c8234dc2c
34.33 - Loading for alternative to eFtZWCVdD/U=
34.33 - Loading for alternative to ZpTIdCj0cTc=
34.33 - No alternative for eFtZWCVdD/U= could be found
34.33 - No alternative for ZpTIdCj0cTc= could be found
35.07 - IPS4 Request Error InternalServerError Internal Server Error - 
 https://vectorplexus.com/api/downloads/files/283 
 {
    "errorCode": "EX6",
    "errorMessage": "UNKNOWN_ERROR"
}
35.07 - Loading for alternative to gsvUHbjw0js=
35.07 - No alternative for gsvUHbjw0js= could be found
35.11 - Hashing Remaining Archives
35.11 - Looking for files to hash
35.54 - Found 2168 total files, 2097 matching filesize
36.17 - Unable to download High_Poly_Head_v1.4_(SE).zip (VectorPlexusOAuthDownloader+State|283|High_Poly_Head_v1.4_(SE).zip|False)
36.17 - Unable to download OBIS SE - Headhunter - patch-52520-1-05-1648483442.zip (NexusDownloader+State|SkyrimSpecialEdition|52520|273294)
36.17 - Unable to download Remastered Ash Piles Of Skyrim-44971-1-1-1611883469.7z (NexusDownloader+State|SkyrimSpecialEdition|44971|182506)
36.17 - Cannot continue, was unable to download one or more archives

**Comment by aaronson2012** [comment]
I had an issue getting the obis and ash piles mods too. you can download them manually from the nexus

https://www.nexusmods.com/skyrimspecialedition/mods/44971?tab=files
https://www.nexusmods.com/skyrimspecialedition/mods/52520?tab=files (update file)

High poly head you can get from here https://drive.google.com/drive/folders/1V_jcYzwTiKnSv8Dbv-7Z0hh9SWbkn6Bi

**Comment by Josemanit132** [comment]
> I had an issue getting the obis and ash piles mods too. you can download them manually from the nexus
> 
> https://www.nexusmods.com/skyrimspecialedition/mods/44971?tab=files https://www.nexusmods.com/skyrimspecialedition/mods/52520?tab=files (update file)
> 
> High poly head you can get from here https://drive.google.com/drive/folders/1V_jcYzwTiKnSv8Dbv-7Z0hh9SWbkn6Bi

Thank you for your help with this mods!! I truly appreciate it!
