### ISSUE TITLE
Error at extracting modlist contents part

### ISSUE THREAD

**Issue by Josemanit132** [TitansBane/Elysium-Remastered#26]
Hello! I was able to get the mods that I was missing, but now I do have another problem when wabbajack is extracting the content from the files. It's a problem that I don't even know what it means, or what I'm missing. 
Could I get some help with this problem? I cannot find anything on google neither.
Thanks!

Encountered error, can't continue - Wabbajack.Common.StatusFeed.Errors._7zipReturnError:

The contents of Elysium_@@_elysium.wabbajack are being extracted to Elysium_@@_elysium.wabbajack using 7zip.exe
37.6 - 7z.exe (7736) StdErr: ERROR: Data Error : 7a187096-bb2f-4ee4-a69f-60bc75a6f5e9
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a1c78e2-848f-43b2-bc45-cfe90773058b
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a21fd52-8f89-4a5a-923d-3805a1603112
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a240762-e2b7-4d74-82b2-dcdb826e16d6
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a244ab1-cbec-4746-95b5-7ad2447d0237
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a2b296b-cae0-4980-b020-76a13cb06161
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a2eb400-008b-4443-b393-6a6bc4a6af83
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a364b88-5a77-4ecc-94fc-2528ca007ad1
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a495583-c221-48b2-998a-3897da9db72e
37.6 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a495f62-e596-4771-8f37-6749d2852de9
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a516ad2-b312-41f2-b043-f93ad8463f0d
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a578d41-711e-4199-adfc-c2043fdc98a8
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a633fdc-6d3f-4e56-8971-32459a647119
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a7a75a3-e565-4e8c-8583-8cf8f7ad8c90
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a7b503e-ec99-4a95-b484-212bfc27373e
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a7df28f-0848-4c5d-8684-416e5516fa97
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a88bfdf-83da-4446-8bf4-309acc816807
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a917207-3791-4c1f-8a67-7e9c412e971e
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7a944f8c-e417-43e8-9483-2a44b903115e
37.61 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7aa23540-a143-477c-bf22-380cb66c4cc4
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7aa9e17c-8c59-4165-bfc9-30f4b83f21af
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7aa9ef17-77ce-4bf7-af53-6c1b24684cba
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ab6e786-4fd4-4103-9d7c-3fa69f8a52d7
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7abd2795-bc3f-47f5-9884-8eef00f9197c
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7abfe84c-de99-4fd7-ad3c-62dd36aa1bf5
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ac29cb4-211e-4fd9-911f-f0dab5fba5ed
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ac89655-c0db-4569-a1ad-edb961d7fc4c
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ac95c28-e842-41a3-9a58-2fe13cb68c8f
37.62 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7acdfe1d-6b77-4581-b0b2-68619762cb42
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7adb3262-9ac8-46e1-a264-bb318cb0531b
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ae7b4f7-f34e-49a1-8d33-1983bc5c9a64
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7aeac925-582c-48b6-92e9-1761dacaa191
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7aec5102-40d8-4b0b-bdf4-5aa78e919864
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7af31e44-8da3-4b54-a5f3-b43ece2ba8a3
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7af3905d-c33a-4685-b145-0762b9534490
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7af3e7e2-fba3-4880-b5a1-6985d3b8cc4e
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7af94f52-e294-4138-b02a-490ddbeb136d
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b012563-bf6e-4874-a559-173568b853b9
37.63 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b26a5de-84cd-4751-90de-8fd1bb0022ae
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b2b21c4-c137-4ab3-a705-8c3468a7f98c
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b314de5-cf6d-4402-969f-10f793af48d0
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b3ef82b-8e94-46f7-ae69-ff547dfab92f
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b431796-d333-437d-b609-bbb48735d29f
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b4617f4-6536-4aae-be58-d998fe616c28
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b4ca854-3920-4173-80de-8a1f0e06013d
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b4d023c-313c-4304-abc9-31d3d04d3583
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b55143f-3deb-4556-983f-33112ceb3532
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b5ff658-3cf3-4da8-89a2-ca463c97f6fb
37.64 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b7bceef-2891-473b-9e3e-eb179be24e56
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b85d6d1-aa31-4918-aad9-aaff5488c544
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b92d871-63d7-4205-93cb-f5c2691c5ec1
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b95cfa0-0426-4124-bc8c-6b16f12dcfbd
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7b979589-1062-4c78-aadd-c6adb0367042
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ba1f9ee-3d31-4564-883d-c83071d2a0e0
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ba32c72-bb35-4784-88fd-6f4a938ac5b0
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bc0a214-6144-49f6-bd53-f890d24a8706
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bc36da0-5d42-4a87-89c4-83e164e2e8b3
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bc9f214-ff8c-4bd0-be65-7a978eef48f9
37.65 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bd34229-53d0-4860-9703-3bf54106086e
37.66 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bd8ee5b-fef7-40ec-bbba-4d0fb1555410
37.66 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bd8fe6b-68be-4b14-b5a5-859f1e0dd052
37.66 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bd90c53-326e-491c-9e87-d5a693640fb0
37.66 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bdd5c21-aae9-479b-8220-528d9962c423
37.66 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bde286f-9d89-4a1d-9607-9a31c8779219
37.66 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bdff92d-ff7a-46cc-ae2b-447db4fa2a33
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7be2f841-e54a-4984-927b-167326a4504b
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bebad9d-a39a-45c6-8cd4-7c780fc16bfa
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7bf8853c-a44e-4ed8-bdb7-6260b26b1a82
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c022bdc-15b4-4719-9735-571e4da894b7
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c0b4b89-584a-43a4-8839-b01db99d2c2d
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c12adc4-b995-4779-a03d-f4b9d39f0e88
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c23c05d-8055-44bb-9853-25d7b0f11884
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c2b81b2-44f5-4d54-ad56-a7fb52a115fe
37.67 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c2ef4bf-ce13-495d-8f51-78b030ca96ae
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c46c0f1-ef49-4d46-a424-c01942e2d664
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c51157b-8434-42e5-8977-afd4771923ee
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c5796fd-40d0-4595-a14e-f0e41a87fb86
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c6cd519-211b-472c-9f1f-d01adc7f3385
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c717028-cda3-4690-8284-5081c87b4159
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c76fae3-0f6b-43ba-9067-1e7d470ff0f3
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c825e76-95d8-4142-a883-e3d9320e64b3
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c89520f-ab7e-4dc6-974c-2a6b4e053115
37.68 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7c8eac94-1d04-4bbd-96c4-b14c3ee108a7
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ca3d436-f4f4-4706-bb88-491ac1b62b46
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ca54972-1bb4-4950-ab9c-c29e9ab02ac7
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cac8898-238c-4278-a4f5-a0289aa6be67
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cc0dffd-3e36-4ba0-97b6-c98f3e67c2cd
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cc5391f-d16f-478e-ba48-25fcf0b6dbc2
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cc9031d-8265-43c6-ba6c-23404d4e9090
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cc9af4f-0d58-4db2-b503-848062947a9d
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cd2e90e-6e49-4d9d-b137-5df0870554d4
37.69 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cdd2cb1-6739-4d02-ba97-a36aeb2a0db0
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ce25f6e-0832-4d0d-9c80-9d71a49e6b08
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ce63f4e-aa5b-48ca-8876-056397f4f669
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ced00e0-f51b-40a6-98e7-eea822e51e4b
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ced7174-0334-497b-9a75-949acf4adcfd
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cee51d1-cb80-4620-985a-636d07a3704f
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cf14e08-f306-44f0-806f-9d82d8a6792a
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cf1aa10-eb3e-4c4c-989f-bf3da7394930
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7cface8b-3e0f-4d8b-a53f-0ef13d83e0bf
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d09c2bd-1eb1-4cd8-9470-e11b36978a6c
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d0b929c-2b34-4691-9509-c3e693cb67bc
37.7 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d249d05-acac-44e5-b999-ffec75ed557f
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d271301-5c38-45f8-9adb-374e74f4ce24
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d2c77c6-e481-4392-8b1f-66697b774478
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d30d240-666b-47fa-9b92-8fa0ca73fb2d
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d336b37-2599-4585-88b2-766a07ab41b4
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d389cd7-7f99-43cb-8ec5-b8f9fdf9cb12
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d3a4f04-ea09-43b9-bb10-6cd3a815fe09
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d3bfeba-3f49-4e7e-a03e-3e98aea13a9b
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d440e21-c594-4fb0-a017-cf15b0bbc8aa
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d4ee00f-2320-45e0-ac2e-62d8fe11095e
37.71 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d662979-52ed-48fb-8395-e74e76b726b7
37.72 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d69ad25-d2eb-4e74-b3b9-eb0439ed8d56
37.72 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d6db48c-5c84-4572-9b9e-6765ad566e80
37.72 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d770ace-3d04-44af-9a67-c66c961bc354
37.72 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d791fb9-9fb4-4331-b997-8c73b9587877
37.72 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d8390cf-3f6b-4c1f-b596-2b7c3ce4d34d
37.72 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d84ecdf-b700-47f6-908b-31604cd5681b
37.72 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d889997-1eea-4ea6-a4c2-ad036d96cc93
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d995a77-1f01-431e-8cb8-27bef0c9128b
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7d9abbed-f952-4984-8793-a447b5dead94
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7da3a038-bf95-421b-ab7c-db49359fc270
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7da53580-1586-4938-ab69-23ecfab8266b
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7da9385a-5587-4918-93d1-80e00dec2332
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7daee1ad-da31-4442-932b-001bc699a432
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7db56b70-2d16-4eb6-892c-97e652d714ba
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7db9e418-5bd5-4120-aec8-6a8f34856051
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7dbd3673-7b9c-452a-8948-f4f852daf075
37.73 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7dc4950a-9d3b-4a1e-8336-a81121846787
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7dc85349-b576-41b2-9a0f-5730edc52247
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7dc8da27-c8c1-4a48-8a93-0bce6c934521
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7dce0c6f-06bc-4f6d-b0cc-15c6e3390325
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7dd47c4f-a8bd-4e93-a1de-21753692558c
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7dd76a75-41b8-4ac3-9561-cdfaaa244631
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ddca0e5-4212-4d33-8aad-fe653a202829
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7df37cb3-b01a-4120-8cbb-ac1956ed71a1
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e0132d8-a259-4d75-91cb-d3866ecd19f6
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e09313c-0a44-4ea6-b77d-9892aa8b412a
37.74 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e09368e-1e21-4d3d-9dd7-ec7f82f659d5
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e09694b-c01b-41b1-8714-78539200cf73
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e0c2966-de1d-4baa-9ef3-e1d157d3b46c
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e11ef59-06d2-4564-9ec4-3dbee39c7471
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e2938d1-4c03-4c4e-be34-c39817416516
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e37396b-e42c-422c-8089-10704061a212
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e381128-69f5-41d6-a51c-f95f4e35e3a6
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e4664e6-855a-4dcf-a0f8-2f8b1f7a4c0b
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e4a23b9-eb16-4f16-ac11-a2403d1cc7a1
37.75 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e505113-d466-4625-9e31-944d6a996b8a
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e583465-e859-4c1b-becf-2b24b832bd8e
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e58a4b7-5eec-4a4a-a5a5-8d1fd368bd78
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e6f5915-74f9-4014-8d57-4a676b21931c
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e70051c-282e-4150-b942-139880687326
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e74bcf7-2afe-46c9-a0cb-a8de0d232beb
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e7d764d-0354-47ef-bec6-f6d4aa0fad16
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e7fd5f6-60b6-4d70-808c-f6562563b559
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e81cb91-1338-4b5a-90c6-4c030b591ef5
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e8c643f-4650-4427-bf1a-17ce2398e263
37.76 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e920a44-0de6-4700-86e4-43d867940d2e
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e937c17-5048-4246-8e6e-aa017bfe1f7f
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7e9af67d-9839-4bf0-ab9e-e7542baa2c9a
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ea59f5f-7fe7-4a32-94a2-222a8c280266
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ea6b9c8-03d1-4524-98a4-ba6355c99e4d
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ec22502-bd30-4691-a0dd-ddfe15f8a99e
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ec80f3d-ff6c-44b4-a057-06a3e0c8f584
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ec9e9fd-42e7-44f4-ba9f-864f03e84df6
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ecaf0f1-9bca-41c9-b8e5-a931e53c9b53
37.77 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ed7abb5-30a9-4245-b7bf-5eab496d391a
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7edbd95a-6698-44e3-8b3e-fd79257641ea
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7edfa7f9-b66e-48d0-9a21-56f4bc5d3df2
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7eece2db-acdc-4aaa-99d6-285c06acc86c
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ef004f6-4049-4e39-b458-074ca09b4779
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ef60979-c48c-419a-9cc8-ede4009b0ad7
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7ef798fa-163e-471c-be65-36d6a1c95716
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f000b0e-92a1-4cd1-811f-2ee7c65912a5
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f0f20a0-ed6b-46f8-b5a9-1c0e6b3eb97e
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f1af95a-7d1e-43b4-aa70-824ef1dea988
37.78 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f2093ad-199f-4556-a7d5-039d692e2a80
37.79 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f228ee6-0f59-4237-aea3-68b2fe7ee260
37.79 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f27e546-114f-4418-8ab8-90fc370da5a0
37.79 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f450326-0fb9-4f49-8478-87e4f60721b4
37.79 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f55d986-9934-4ef3-956e-a245b9678e78
37.79 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f57bb45-b598-469a-a5e1-88e7ef9ebb15
37.79 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f58a3d1-c60d-42c4-9386-7fe25c193d6b
37.79 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f6abe4f-a922-4d59-a5b6-fb9a9d492f8e
37.79 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f6b9292-8ef7-400c-8f44-fd406f1ea423
37.8 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f7a7383-2a75-413d-8945-e9a3db1bda71
37.8 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f87cd2c-b80e-4be0-a932-72d3d50ad779
37.8 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f881db2-b01d-434b-8c2f-2631f953ef78
37.8 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f8b6af1-2645-4b71-a570-fe0179d63d55
37.8 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f8d4aad-c785-442a-a8d7-300631ca0ec0
37.8 - 7z.exe (7736) StdErr: ERROR: Headers Error : 7f8e38c1-0081-4add-ad4b-5ed072e27c38
67.87 - 7Zip returned an error while executing

72.1 - File hash check (-42) 4f04c55d2bc0afe4ccb523a180fb8d508b120d370b1aee66a8e80c6c8234dc2c
72.13 - Encountered error, can't continue - Wabbajack.Common.StatusFeed.Errors._7zipReturnError: Exception of type 'Wabbajack.Common.StatusFeed.Errors._7zipReturnError' was thrown.
   at Wabbajack.Common.Utils.ErrorThrow(IException err) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Common\Logging.cs:line 121
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtractWith7Zip[T](WorkQueue queue, IStreamFactory sf, FileType sig, Predicate`1 shouldExtract, Func`3 mapfn, AbsolutePath tempPath, HashSet`1 onlyFiles) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 243
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtractWith7Zip[T](WorkQueue queue, IStreamFactory sf, FileType sig, Predicate`1 shouldExtract, Func`3 mapfn, AbsolutePath tempPath, HashSet`1 onlyFiles) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 275
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtract[T](WorkQueue queue, IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, Nullable`1 tempFolder, HashSet`1 onlyFiles) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 87
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtract[T](WorkQueue queue, IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, Nullable`1 tempFolder, HashSet`1 onlyFiles) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 114
   at Wabbajack.VirtualFileSystem.FileExtractor2.ExtractAll(WorkQueue queue, AbsolutePath src, AbsolutePath dest) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 282
   at Wabbajack.Lib.AInstaller.ExtractModlist() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 55
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 169
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
72.21 - File hash check (-42) 4f04c55d2bc0afe4ccb523a180fb8d508b120d370b1aee66a8e80c6c8234dc2c

**Comment by Sorkys** [comment]
I got the same problem now :/
