### ISSUE TITLE
Installation failed, 7zip returned Error while extracting.

### ISSUE THREAD

**Issue by JEUSBURRTO** [TitansBane/Elysium-Remastered#3]
I tried finding a similar issue but could not. everything downloaded great but I received this error during instalation.
(I am relatively new to modding sorry if this is a simple or duplicate issue..)

0.13 - Wabbajack Build - 9d251cda832b7478c9480345ee829f46e02df999
0.14 - Running in C:\Wabbajack\2.5.3.7
0.14 - Detected Windows Version: 10.0.22000.0
0.14 - System settings - (31.8GB RAM) (5GB Page), Display: 1920 x 1080 (9.8GB VRAM - VideoMemorySizeMb=10240)
0.14 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.15 - Getting new Wabbajack version list
0.15 - Steam: Found no Regex matches in Steam Config at c:/steam\config\config.vdf
0.16 - Steam: Found game Steamworks Common Redistributables (228980) at "C:\Steam\steamapps\common\Steamworks Shared"
0.16 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "C:\Steam\steamapps\common\Skyrim Special Edition"
0.16 - Steam: Found game Steamworks Common Redistributables (228980) at "c:/steam\steamapps\common\Steamworks Shared"
0.16 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "c:/steam\steamapps\common\Skyrim Special Edition"
0.16 - GOG: GOG was not found in the registry
0.16 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.16 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.17 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.5 - Wabbajack Version: 2.5.3.7
0.75 - Build server is alive
0.75 - File hash check (-42) b356e2b546b704fec65a6347d29908259382999692ecc9c1b26f6d2839fee841
0.75 - Build server is alive
0.76 - File hash check (-42) b356e2b546b704fec65a6347d29908259382999692ecc9c1b26f6d2839fee841
17.52 - Starting to install Elysium Remastered
17.53 - Cleaning VFS, this may take a bit of time
17.54 - Starting Installer Task
17.54 - Installation has Started
17.54 - File hash check (-42) b356e2b546b704fec65a6347d29908259382999692ecc9c1b26f6d2839fee841
17.67 - Configuring Processor
17.68 - Install Folder: C:\Elysium Remastered
17.68 - Downloads Folder: C:\Elysium Remastered\downloads
17.68 - Game Folder: C:\Steam\steamapps\common\Skyrim Special Edition
17.68 - Wabbajack Folder: C:\Wabbajack\2.5.3.7
17.68 - Drive watcher is starting. Will warn at 8GB and error at 4GB
17.68 - Starting Drive watcher on C:\ currently 1.6TB free out of 1.8TB
17.68 - Validating Game ESMs
17.69 - Creating Output Folders
17.74 - Caught error getting disk info: Sequence contains no elements. Treating disk as Unspecified.
17.74 - Optimizing ModList
17.74 - Optimizing ModList directives
19.05 - Looking for files to delete
19.07 - Cleaning empty folders
19.64 - Looking for unmodified files
19.98 - Updating ModList
19.98 - Optimized 218352 directives to 218352 required
20.01 - Hashing Archives
20.01 - Looking for files to hash
20.07 - Found 1957 total files, 1885 matching filesize
20.22 - Downloading Missing Archives
20.22 - Missing 0 archives
20.22 - Getting Nexus API Key, if a browser appears, please accept
20.22 - Loading server whitelist
20.29 - Loaded permissions for 652 servers and 292 Google Drive files
20.34 - Hashing Remaining Archives
20.34 - Looking for files to hash
20.4 - Found 1957 total files, 1885 matching filesize
20.56 - Extracting Modlist contents
20.56 - Extracting C:\Wabbajack\downloaded_mod_lists\elysium.wabbajack
20.56 - The contents of elysium.wabbajack are being extracted to elysium.wabbajack using 7zip.exe
30.29 - 7z.exe (15744) StdErr: ERROR: Data Error : f3ab08d0-b350-4062-9bd3-ae8d7f61b453
30.29 - 7z.exe (15744) StdErr: ERROR: Headers Error : f3bf284f-0ead-443f-89e8-02cbe71d29f3
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f3c3aea8-055b-48d1-b41f-11daf41c72b7
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f3c47a02-1712-490c-a271-bbe27d132733
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f3d30211-6302-4317-96df-c78d33dd33ca
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f3eb942a-4ff4-4357-90a8-6ad3f974fc74
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f3ef1345-e526-41ac-b77f-6b388f000804
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f3f7e1f8-7d88-4128-9154-f9ebe23f7e05
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f3f86f33-8245-4ea5-8f98-8f4c82cb68bb
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f400e2d7-c9d5-4424-988e-bd4e1f8b3376
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f401c43f-9a5f-4817-a545-bc060492a648
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4111f72-6e3e-48a5-9dbf-2dcc01fd7119
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f41fb230-75e2-40c5-92e8-1d43d5e78f22
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4203a98-c2dc-4b45-bdd9-cdf78ebb34e1
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4264830-3040-4a5a-b126-4c4e8094f5fa
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f42e7663-baf5-46ac-a638-e16dd58d41f4
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f44db9d1-1fed-4f18-b7c5-234107a36ca6
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f453aabb-0015-4b12-a9ca-51c1aec2b394
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f465a044-4d4f-4d54-b2bd-e69922d325d7
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f46a5121-9924-459f-b843-bdfefcdcbff8
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f46ae097-6c5c-45a4-8d44-9cc36a34b72f
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f48179b3-5524-4b8e-b659-037585320b22
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4848817-d60b-42e9-a94c-f6111e1f7bea
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f49c6b52-3d39-41ad-a27a-4c42cbf3631d
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4a501f5-b8c9-4454-9c0e-94273bba4474
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4b3d967-a92d-43e9-9a05-dcd9e93481f2
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4b8ef80-0f98-4131-b95c-0c05c00305a1
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4c36917-9b4f-4ee1-9b23-b040d3d89f00
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4c4427d-51cd-4e52-8998-2dfd692de889
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4c822a8-6262-46d7-85c1-a1807dcb532f
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4cc8919-bced-4e73-90ee-a60dc3c00e1e
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4cfaf54-4178-4dea-a24a-242063420ebd
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f4e19c13-6e6c-45c4-ac7d-ec0eb026c0b3
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f5044fd9-1c5a-4824-9133-bd4a91f95277
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f50b1bfa-c517-435b-a1fe-e0fed154e8de
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f51215e1-f6c0-495d-9aea-d7b3c226465a
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f51b2aa9-3332-461a-8312-694ebc42be99
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f51bc5ec-28c5-4c28-8aac-2f4f6f1786d9
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f51c4221-35c5-4ded-9734-8c221b3ddf8c
30.3 - 7z.exe (15744) StdErr: ERROR: Headers Error : f5218d96-8f89-4b94-8bc7-6587edd6bf9e
30.31 - 7z.exe (15744) StdErr: ERROR: Headers Error : f5243603-cbf9-4cd3-9061-db67f6c222c9
30.31 - 7z.exe (15744) StdErr: ERROR: Headers Error : f526658a-25dc-4eb4-b3af-c4c2e38f1977
30.31 - 7z.exe (15744) StdErr: ERROR: Headers Error : f52d8b22-504a-4beb-9be3-9707baf35f70
30.31 - 7z.exe (15744) StdErr: ERROR: Headers Error : f5301bd1-bbaf-4996-aaa3-30d0ff6edde3
30.31 - 7z.exe (15744) StdErr: ERROR: Headers Error : f53c57c6-e2c4-4347-b81f-4c3d1314cc75
30.31 - 7z.exe (15744) StdErr: ERROR: Headers Error : f53d0910-2f49-4097-8312-dbbb1a77cf49
30.9 - 7Zip returned an error while executing

31.73 - File hash check (-42) b356e2b546b704fec65a6347d29908259382999692ecc9c1b26f6d2839fee841
31.74 - Encountered error, can't continue - Wabbajack.Common.StatusFeed.Errors._7zipReturnError: Exception of type 'Wabbajack.Common.StatusFeed.Errors._7zipReturnError' was thrown.
   at Wabbajack.Common.Utils.ErrorThrow(IException err) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Common\Logging.cs:line 121
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtractWith7Zip[T](WorkQueue queue, IStreamFactory sf, FileType sig, Predicate`1 shouldExtract, Func`3 mapfn, AbsolutePath tempPath, HashSet`1 onlyFiles) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 243
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtractWith7Zip[T](WorkQueue queue, IStreamFactory sf, FileType sig, Predicate`1 shouldExtract, Func`3 mapfn, AbsolutePath tempPath, HashSet`1 onlyFiles) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 275
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtract[T](WorkQueue queue, IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, Nullable`1 tempFolder, HashSet`1 onlyFiles) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 87
   at Wabbajack.VirtualFileSystem.FileExtractor2.GatheringExtract[T](WorkQueue queue, IStreamFactory sFn, Predicate`1 shouldExtract, Func`3 mapfn, Nullable`1 tempFolder, HashSet`1 onlyFiles) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 114
   at Wabbajack.VirtualFileSystem.FileExtractor2.ExtractAll(WorkQueue queue, AbsolutePath src, AbsolutePath dest) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.VirtualFileSystem\FileExtractor2\FileExtractor.cs:line 282
   at Wabbajack.Lib.AInstaller.ExtractModlist() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 54
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 169
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
31.89 - File hash check (-42) b356e2b546b704fec65a6347d29908259382999692ecc9c1b26f6d2839fee841

**Comment by Sorkys** [comment]
Hey @JEUSBURRTO and @TitansBane,
could I please get the solution of this error? Is it something I have to solve on my PC?
I am getting (as far as I can tell) the same error.

Thank you very much!
