### ISSUE TITLE
Download Issues 

### ISSUE THREAD

**Issue by Killbot64** [TitansBane/Elysium-Remastered#35]
Hey there! Also getting some issues as some other people, but there's alot going on, so I'll keep an eye on those posts as well, but im getting like all the issues.

**Getting a bunch of errors in this format:**
313.21 - (Retry 5 of 5), got exception (2) The system cannot find the file specified: [G:\SteamLibrary\steamapps\common\Skyrim Special Edition\Data\ccasvsse001-almsivi.bsa], waiting 1600ms

**And then this:**
314.81 - Loading for alternative to RH5s6TYWBpg=
314.81 - No alternative for RH5s6TYWBpg= could be found
314.82 - Loading for alternative to iSJ0sFrw2bE=
314.82 - Loading for alternative to ewc8cVgdm24=
314.82 - Loading for alternative to OFF/XldDPuU=
314.82 - No alternative for iSJ0sFrw2bE= could be found
314.82 - No alternative for ewc8cVgdm24= could be found
314.82 - No alternative for OFF/XldDPuU= could be found
314.91 - Hashing Remaining Archives
314.91 - Looking for files to hash
314.99 - Found 2015 total files, 1975 matching filesize
315.25 - Unable to download Data_ccafdsse001-dwesanctuary.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccafdsse001-dwesanctuary.bsa)
315.25 - Unable to download Data_ccafdsse001-dwesanctuary.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccafdsse001-dwesanctuary.esm)
315.25 - Unable to download Data_ccasvsse001-almsivi.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccasvsse001-almsivi.bsa)
315.25 - Unable to download Data_ccasvsse001-almsivi.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccasvsse001-almsivi.esm)
315.25 - Unable to download Data_ccbgssse002-exoticarrows.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse002-exoticarrows.bsa)
315.25 - Unable to download Data_ccbgssse002-exoticarrows.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse002-exoticarrows.esl)
315.25 - Unable to download Data_ccbgssse003-zombies.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse003-zombies.bsa)
315.25 - Unable to download Data_ccbgssse003-zombies.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse003-zombies.esl)
315.25 - Unable to download Data_ccbgssse004-ruinsedge.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse004-ruinsedge.bsa)
315.25 - Unable to download Data_ccbgssse004-ruinsedge.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse004-ruinsedge.esl)
315.25 - Unable to download Data_ccbgssse005-goldbrand.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse005-goldbrand.bsa)
315.25 - Unable to download Data_ccbgssse005-goldbrand.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse005-goldbrand.esl)
315.25 - Unable to download Data_ccbgssse006-stendarshammer.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse006-stendarshammer.bsa)
315.25 - Unable to download Data_ccbgssse006-stendarshammer.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse006-stendarshammer.esl)
315.25 - Unable to download Data_ccbgssse007-chrysamere.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse007-chrysamere.bsa)
315.25 - Unable to download Data_ccbgssse007-chrysamere.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse007-chrysamere.esl)
315.25 - Unable to download Data_ccbgssse008-wraithguard.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse008-wraithguard.bsa)
315.25 - Unable to download Data_ccbgssse008-wraithguard.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse008-wraithguard.esl)
315.25 - Unable to download Data_ccbgssse010-petdwarvenarmoredmudcrab.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse010-petdwarvenarmoredmudcrab.bsa)
315.25 - Unable to download Data_ccbgssse010-petdwarvenarmoredmudcrab.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse010-petdwarvenarmoredmudcrab.esl)
315.25 - Unable to download Data_ccbgssse011-hrsarmrelvn.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse011-hrsarmrelvn.bsa)
315.25 - Unable to download Data_ccbgssse011-hrsarmrelvn.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse011-hrsarmrelvn.esl)
315.25 - Unable to download Data_ccbgssse012-hrsarmrstl.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse012-hrsarmrstl.bsa)
315.25 - Unable to download Data_ccbgssse012-hrsarmrstl.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse012-hrsarmrstl.esl)
315.25 - Unable to download Data_ccbgssse013-dawnfang.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse013-dawnfang.bsa)
315.25 - Unable to download Data_ccbgssse013-dawnfang.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse013-dawnfang.esl)
315.25 - Unable to download Data_ccbgssse014-spellpack01.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse014-spellpack01.bsa)
315.25 - Unable to download Data_ccbgssse014-spellpack01.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse014-spellpack01.esl)
315.25 - Unable to download Data_ccbgssse016-umbra.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse016-umbra.bsa)
315.25 - Unable to download Data_ccbgssse016-umbra.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse016-umbra.esm)
315.25 - Unable to download Data_ccbgssse018-shadowrend.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse018-shadowrend.bsa)
315.25 - Unable to download Data_ccbgssse018-shadowrend.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse018-shadowrend.esl)
315.25 - Unable to download Data_ccbgssse019-staffofsheogorath.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse019-staffofsheogorath.bsa)
315.25 - Unable to download Data_ccbgssse019-staffofsheogorath.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse019-staffofsheogorath.esl)
315.25 - Unable to download Data_ccbgssse020-graycowl.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse020-graycowl.bsa)
315.25 - Unable to download Data_ccbgssse020-graycowl.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse020-graycowl.esl)
315.25 - Unable to download Data_ccbgssse021-lordsmail.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse021-lordsmail.bsa)
315.25 - Unable to download Data_ccbgssse021-lordsmail.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse021-lordsmail.esl)
315.25 - Unable to download Data_ccbgssse031-advcyrus.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse031-advcyrus.bsa)
315.25 - Unable to download Data_ccbgssse031-advcyrus.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse031-advcyrus.esm)
315.25 - Unable to download Data_ccbgssse034-mntuni.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse034-mntuni.bsa)
315.25 - Unable to download Data_ccbgssse034-mntuni.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse034-mntuni.esl)
315.25 - Unable to download Data_ccbgssse035-petnhound.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse035-petnhound.bsa)
315.25 - Unable to download Data_ccbgssse035-petnhound.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse035-petnhound.esl)
315.25 - Unable to download Data_ccbgssse036-petbwolf.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse036-petbwolf.bsa)
315.25 - Unable to download Data_ccbgssse036-petbwolf.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse036-petbwolf.esl)
315.26 - Unable to download Data_ccbgssse038-bowofshadows.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse038-bowofshadows.bsa)
315.26 - Unable to download Data_ccbgssse038-bowofshadows.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse038-bowofshadows.esl)
315.26 - Unable to download Data_ccbgssse040-advobgobs.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse040-advobgobs.bsa)
315.26 - Unable to download Data_ccbgssse040-advobgobs.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse040-advobgobs.esl)
315.26 - Unable to download Data_ccbgssse041-netchleather.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse041-netchleather.bsa)
315.26 - Unable to download Data_ccbgssse041-netchleather.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse041-netchleather.esl)
315.26 - Unable to download Data_ccbgssse043-crosselv.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse043-crosselv.bsa)
315.26 - Unable to download Data_ccbgssse043-crosselv.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse043-crosselv.esl)
315.26 - Unable to download Data_ccbgssse045-hasedoki.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse045-hasedoki.bsa)
315.26 - Unable to download Data_ccbgssse045-hasedoki.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse045-hasedoki.esl)
315.26 - Unable to download Data_ccbgssse050-ba_daedric.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse050-ba_daedric.bsa)
315.26 - Unable to download Data_ccbgssse050-ba_daedric.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse050-ba_daedric.esl)
315.26 - Unable to download Data_ccbgssse051-ba_daedricmail.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse051-ba_daedricmail.bsa)
315.26 - Unable to download Data_ccbgssse051-ba_daedricmail.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse051-ba_daedricmail.esl)
315.26 - Unable to download Data_ccbgssse052-ba_iron.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse052-ba_iron.bsa)
315.26 - Unable to download Data_ccbgssse052-ba_iron.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse052-ba_iron.esl)
315.26 - Unable to download Data_ccbgssse053-ba_leather.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse053-ba_leather.bsa)
315.26 - Unable to download Data_ccbgssse053-ba_leather.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse053-ba_leather.esl)
315.26 - Unable to download Data_ccbgssse054-ba_orcish.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse054-ba_orcish.bsa)
315.26 - Unable to download Data_ccbgssse054-ba_orcish.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse054-ba_orcish.esl)
315.26 - Unable to download Data_ccbgssse055-ba_orcishscaled.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse055-ba_orcishscaled.bsa)
315.26 - Unable to download Data_ccbgssse055-ba_orcishscaled.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse055-ba_orcishscaled.esl)
315.26 - Unable to download Data_ccbgssse056-ba_silver.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse056-ba_silver.bsa)
315.26 - Unable to download Data_ccbgssse056-ba_silver.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse056-ba_silver.esl)
315.26 - Unable to download Data_ccbgssse057-ba_stalhrim.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse057-ba_stalhrim.bsa)
315.26 - Unable to download Data_ccbgssse057-ba_stalhrim.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse057-ba_stalhrim.esl)
315.26 - Unable to download Data_ccbgssse058-ba_steel.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse058-ba_steel.bsa)
315.26 - Unable to download Data_ccbgssse058-ba_steel.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse058-ba_steel.esl)
315.26 - Unable to download Data_ccbgssse059-ba_dragonplate.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse059-ba_dragonplate.bsa)
315.26 - Unable to download Data_ccbgssse059-ba_dragonplate.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse059-ba_dragonplate.esl)
315.26 - Unable to download Data_ccbgssse060-ba_dragonscale.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse060-ba_dragonscale.bsa)
315.26 - Unable to download Data_ccbgssse060-ba_dragonscale.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse060-ba_dragonscale.esl)
315.26 - Unable to download Data_ccbgssse061-ba_dwarven.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse061-ba_dwarven.bsa)
315.26 - Unable to download Data_ccbgssse061-ba_dwarven.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse061-ba_dwarven.esl)
315.26 - Unable to download Data_ccbgssse062-ba_dwarvenmail.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse062-ba_dwarvenmail.bsa)
315.26 - Unable to download Data_ccbgssse062-ba_dwarvenmail.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse062-ba_dwarvenmail.esl)
315.26 - Unable to download Data_ccbgssse063-ba_ebony.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse063-ba_ebony.bsa)
315.26 - Unable to download Data_ccbgssse063-ba_ebony.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse063-ba_ebony.esl)
315.26 - Unable to download Data_ccbgssse064-ba_elven.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse064-ba_elven.bsa)
315.26 - Unable to download Data_ccbgssse064-ba_elven.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse064-ba_elven.esl)
315.26 - Unable to download Data_ccbgssse066-staves.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse066-staves.bsa)
315.26 - Unable to download Data_ccbgssse066-staves.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse066-staves.esl)
315.26 - Unable to download Data_ccbgssse067-daedinv.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse067-daedinv.bsa)
315.26 - Unable to download Data_ccbgssse067-daedinv.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse067-daedinv.esm)
315.27 - Unable to download Data_ccbgssse068-bloodfall.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse068-bloodfall.bsa)
315.27 - Unable to download Data_ccbgssse068-bloodfall.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse068-bloodfall.esl)
315.27 - Unable to download Data_ccbgssse069-contest.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse069-contest.bsa)
315.27 - Unable to download Data_ccbgssse069-contest.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccbgssse069-contest.esl)
315.27 - Unable to download Data_cccbhsse001-gaunt.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cccbhsse001-gaunt.bsa)
315.27 - Unable to download Data_cccbhsse001-gaunt.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cccbhsse001-gaunt.esl)
315.27 - Unable to download Data_ccedhsse001-norjewel.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccedhsse001-norjewel.bsa)
315.27 - Unable to download Data_ccedhsse001-norjewel.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccedhsse001-norjewel.esl)
315.27 - Unable to download Data_ccedhsse002-splkntset.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccedhsse002-splkntset.bsa)
315.27 - Unable to download Data_ccedhsse002-splkntset.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccedhsse002-splkntset.esl)
315.27 - Unable to download Data_ccedhsse003-redguard.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccedhsse003-redguard.bsa)
315.27 - Unable to download Data_ccedhsse003-redguard.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccedhsse003-redguard.esl)
315.27 - Unable to download Data_cceejsse001-hstead.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse001-hstead.bsa)
315.27 - Unable to download Data_cceejsse001-hstead.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse001-hstead.esm)
315.27 - Unable to download Data_cceejsse002-tower.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse002-tower.bsa)
315.27 - Unable to download Data_cceejsse002-tower.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse002-tower.esl)
315.27 - Unable to download Data_cceejsse003-hollow.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse003-hollow.bsa)
315.27 - Unable to download Data_cceejsse003-hollow.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse003-hollow.esl)
315.27 - Unable to download Data_cceejsse004-hall.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse004-hall.bsa)
315.27 - Unable to download Data_cceejsse004-hall.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse004-hall.esl)
315.27 - Unable to download Data_cceejsse005-cave.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse005-cave.bsa)
315.27 - Unable to download Data_cceejsse005-cave.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cceejsse005-cave.esm)
315.27 - Unable to download Data_ccffbsse001-imperialdragon.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccffbsse001-imperialdragon.bsa)
315.27 - Unable to download Data_ccffbsse001-imperialdragon.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccffbsse001-imperialdragon.esl)
315.27 - Unable to download Data_ccffbsse002-crossbowpack.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccffbsse002-crossbowpack.bsa)
315.27 - Unable to download Data_ccffbsse002-crossbowpack.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccffbsse002-crossbowpack.esl)
315.27 - Unable to download Data_ccfsvsse001-backpacks.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccfsvsse001-backpacks.bsa)
315.27 - Unable to download Data_ccfsvsse001-backpacks.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccfsvsse001-backpacks.esl)
315.27 - Unable to download Data_cckrtsse001_altar.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cckrtsse001_altar.bsa)
315.27 - Unable to download Data_cckrtsse001_altar.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cckrtsse001_altar.esl)
315.27 - Unable to download Data_ccmtysse001-knightsofthenine.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccmtysse001-knightsofthenine.bsa)
315.28 - Unable to download Data_ccmtysse001-knightsofthenine.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccmtysse001-knightsofthenine.esl)
315.28 - Unable to download Data_ccmtysse002-ve.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccmtysse002-ve.bsa)
315.28 - Unable to download Data_ccmtysse002-ve.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccmtysse002-ve.esl)
315.28 - Unable to download Data_ccpewsse002-armsofchaos.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccpewsse002-armsofchaos.bsa)
315.28 - Unable to download Data_ccpewsse002-armsofchaos.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccpewsse002-armsofchaos.esl)
315.28 - Unable to download Data_ccqdrsse002-firewood.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccqdrsse002-firewood.bsa)
315.28 - Unable to download Data_ccqdrsse002-firewood.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccqdrsse002-firewood.esl)
315.28 - Unable to download Data_ccrmssse001-necrohouse.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccrmssse001-necrohouse.bsa)
315.28 - Unable to download Data_ccrmssse001-necrohouse.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccrmssse001-necrohouse.esl)
315.28 - Unable to download Data_cctwbsse001-puzzledungeon.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cctwbsse001-puzzledungeon.bsa)
315.28 - Unable to download Data_cctwbsse001-puzzledungeon.esm (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\cctwbsse001-puzzledungeon.esm)
315.28 - Unable to download Data_ccvsvsse001-winter.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccvsvsse001-winter.bsa)
315.28 - Unable to download Data_ccvsvsse001-winter.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccvsvsse001-winter.esl)
315.28 - Unable to download Data_ccvsvsse002-pets.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccvsvsse002-pets.bsa)
315.28 - Unable to download Data_ccvsvsse002-pets.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccvsvsse002-pets.esl)
315.28 - Unable to download Data_ccvsvsse003-necroarts.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccvsvsse003-necroarts.bsa)
315.28 - Unable to download Data_ccvsvsse003-necroarts.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccvsvsse003-necroarts.esl)
315.28 - Unable to download Data_ccvsvsse004-beafarmer.bsa (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccvsvsse004-beafarmer.bsa)
315.28 - Unable to download Data_ccvsvsse004-beafarmer.esl (GameFileSourceDownloader+State|SkyrimSpecialEdition|1.6.353.0|data\ccvsvsse004-beafarmer.esl)
315.28 - Cannot continue, was unable to download one or more archives
315.28 - File hash check (-42) 1573a803371cec63a293df55e86bea0e046042f349d904bbffb545a51b43daf3
315.31 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in c:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
315.47 - File hash check (-42) 1573a803371cec63a293df55e86bea0e046042f349d904bbffb545a51b43daf3

**Comment by PhaDlaDy** [comment]
Try changing the game language in steam to English

**Comment by Killbot64** [comment]
> Try changing the game language in steam to English

Is this supposed to be a troll? lmfao

**Comment by jswent** [comment]
Could anyone be kind enough to upload the files unable to be downloaded to google drive or some such thing so that we can manually install them?

**Comment by PhaDlaDy** [comment]
> 

Nope thats the solution of most of these errors.

**Comment by jswent** [comment]
> 

My game language is already in English tho and I'm still getting these errors, It's pretty obvious the loader can't source the files required for the install, my guess is because of Vector Plexus being down.

**Comment by Killbot64** [comment]
> > 
> 
> Nope thats the solution of most of these errors.

LMFAO then you're stupid because my game language is and always has been english rofl

**Comment by romsi1983** [comment]
Is it possible to download these files manually and revive the installation somehow?

**Comment by AmarasXV** [comment]
UP, i got the same issue, have you found a way to solve it ?

**Comment by PunchlinePanda** [comment]
Solution: Buy the Creation Club Content and install it (as instructed in the README). It is NECESSARY. The Error Messages you get are all from the Creation Club stuff (cc..xxx...) if you check the names. So - install it, then you shouldnt get any more issues

**Comment by Killbot64** [comment]
> Solution: Buy the Creation Club Content and install it (as instructed in the README). It is NECESSARY. The Error Messages you get are all from the Creation Club stuff (cc..xxx...) if you check the names. So - install it, then you shouldnt get any more issues

A proper response finally, thanks so much, I don't know how I missed this! Guess I'm so used to packs not supporting it haha. Would you happen to know what files I actually need in my isolated installation for this? Because I have the creation club content, but I don't know exactly what files need to go where.

**Comment by finesse357** [comment]
?

**Comment by Sharogen** [comment]
Just in case you find yourself here with the same issue, there's an option when you go into the creation club to "download all owned content." When I first launched the game it seems like it only download most of them, but missed a few key anniversary ones.

**Comment by breadland** [comment]
And in case all the fixes listed above still weren't enough, make sure to turn off your VPN during the CC downloads if you use one.
Even if the game claims that everything was downloaded and no error has occurred.

Took me a while to figure that one out.
