### ISSUE TITLE
Mega File Taken Down

### ISSUE THREAD

**Issue by Ankmeister** [TitansBane/Elysium-Remastered#38]
Link information:
https://mega.nz/file/4RclCSoZ#rlwTxUt8iRg1DEHvuNuB80Mdu62Kdq6Gzo3NY4xqnPg

Error routing:
File hash check (-42) ff6e1e901e50a5d59fcea2461dd1f24e42237db93661b398b7b37190f548cf89
147 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/4RclCSoZ#rlwTxUt8iRg1DEHvuNuB80Mdu62Kdq6Gzo3NY4xqnPg failed validation

Tried going to the link via a browser, but no file exists.
Can someone upload a working link, provide the file, or is there a way to skip past it?

**Comment by Ankmeister** [comment]
Link information:
https://mega.nz/file/4RclCSoZ#rlwTxUt8iRg1DEHvuNuB80Mdu62Kdq6Gzo3NY4xqnPg

Error routing:
File hash check (-42) ff6e1e901e50a5d59fcea2461dd1f24e42237db93661b398b7b37190f548cf89
147 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/4RclCSoZ#rlwTxUt8iRg1DEHvuNuB80Mdu62Kdq6Gzo3NY4xqnPg failed validation

Tried going to the link via a browser, but no file exists.
Can someone upload a working link, provide the file, or is there a way to skip past it?

**Comment by Edzward** [comment]
Can confirm. Came just to post the exact same thing. 
It seems to be the **Core Files**, so I doubt it will work without them. :(
If some can share the file would be appreciated. Meanwhile I'll check if I can find a mirror somewhere else.

**Comment by Ankmeister** [comment]
> @Ankmeister UPDATE: Found it: https://drive.google.com/u/0/uc?id=1fB53OG8sVI3-R54utXWsyY22M4wXg8hM
> 
> Can confirm. Came just to post the exact same thing. It seems to be the **Core Files**, so I doubt it will work without them. :( If some can share the file would be appreciated. Meanwhile I'll check if I can find a mirror somewhere else.
> 
> EDIT: I'll try to ask for help on r/Wabbajack
> 
> EDIT2: Link to [the reddit post](https://www.reddit.com/r/wabbajack/comments/velqu2/help_elysium_remastered_core_files_offline_on_mega/).

Thanks!
But this file is no longer available, it seems. "The requested URL was not found on this server. That’s all we know."
Did I miss something? I guess I was too slow to get it :/

**Comment by Ankmeister** [comment]
Latest update seems to have fixed the problem.
I am just redownloaded the Elysium mod in Wabbajack

**Comment by Edzward** [comment]
> > @Ankmeister UPDATE: Found it: https://drive.google.com/u/0/uc?id=1fB53OG8sVI3-R54utXWsyY22M4wXg8hM
> > 
> > Can confirm. Came just to post the exact same thing. It seems to be the **Core Files**, so I doubt it will work without them. :( If some can share the file would be appreciated. Meanwhile I'll check if I can find a mirror somewhere else.
> > 
> > EDIT: I'll try to ask for help on r/Wabbajack
> > 
> > EDIT2: Link to [the reddit post](https://www.reddit.com/r/wabbajack/comments/velqu2/help_elysium_remastered_core_files_offline_on_mega/).
> 
> @Edzward Thanks!
> But this file is no longer available, it seems. "The requested URL was not found on this server. That’s all we know."
> Did I miss something? I guess I was too slow to get it :/

Sorry. Forgot to update!
The Official installer was updated to 1.7.1 and now all the issues were resolved now.
Just go to the Wabbajack website and re-download the installer.
