### ISSUE TITLE
Encountered error, can't continue - System.Exception: File MegaDownloader+State

### ISSUE THREAD

**Issue by Danoshii** [TitansBane/Elysium-Remastered#4]
Last night I was downloading Elysium Remastered from using wabbajack and there is the full log I got from the instalation

0.3 - Wabbajack Build - 9d251cda832b7478c9480345ee829f46e02df999
0.3 - Running in D:\Downloads\2.5.3.7
0.36 - Detected Windows Version: 10.0.19042.0
0.36 - System settings - (31.9GB RAM) (4.8GB Page), Display: 1920 x 1080 (7.9GB VRAM - VideoMemorySizeMb=10240)
0.36 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.37 - Getting new Wabbajack version list
0.43 - Steam: Found no Regex matches in Steam Config at d:/programs/steam\config\config.vdf
0.44 - Steam: Found game Rogue Legacy 2 (1253920) at "D:\Programs\Steam\steamapps\common\Rogue Legacy 2"
0.44 - Steam: Found game Goose Goose Duck (1568590) at "D:\Programs\Steam\steamapps\common\Goose Goose Duck"
0.44 - Steam: Found game Lost Ark (1599340) at "D:\Programs\Steam\steamapps\common\Lost Ark"
0.44 - Steam: Found game Steamworks Common Redistributables (228980) at "D:\Programs\Steam\steamapps\common\Steamworks Shared"
0.44 - Steam: Found game Unturned (304930) at "D:\Programs\Steam\steamapps\common\Unturned"
0.44 - Steam: Found game Geometry Dash (322170) at "D:\Programs\Steam\steamapps\common\Geometry Dash"
0.44 - Steam: Found game Wallpaper Engine (431960) at "D:\Programs\Steam\steamapps\common\wallpaper_engine"
0.44 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\Programs\Steam\steamapps\common\Skyrim Special Edition"
0.44 - Steam: Found game Counter-Strike: Global Offensive (730) at "D:\Programs\Steam\steamapps\common\Counter-Strike Global Offensive"
0.44 - Steam: Found game Among Us (945360) at "D:\Programs\Steam\steamapps\common\Among Us"
0.44 - Steam: Found game Rogue Legacy 2 (1253920) at "d:/programs/steam\steamapps\common\Rogue Legacy 2"
0.44 - Steam: Found game Goose Goose Duck (1568590) at "d:/programs/steam\steamapps\common\Goose Goose Duck"
0.44 - Steam: Found game Lost Ark (1599340) at "d:/programs/steam\steamapps\common\Lost Ark"
0.45 - Steam: Found game Steamworks Common Redistributables (228980) at "d:/programs/steam\steamapps\common\Steamworks Shared"
0.45 - Steam: Found game Unturned (304930) at "d:/programs/steam\steamapps\common\Unturned"
0.45 - Steam: Found game Geometry Dash (322170) at "d:/programs/steam\steamapps\common\Geometry Dash"
0.45 - Steam: Found game Wallpaper Engine (431960) at "d:/programs/steam\steamapps\common\wallpaper_engine"
0.45 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "d:/programs/steam\steamapps\common\Skyrim Special Edition"
0.45 - Steam: Found game Counter-Strike: Global Offensive (730) at "d:/programs/steam\steamapps\common\Counter-Strike Global Offensive"
0.45 - Steam: Found game Among Us (945360) at "d:/programs/steam\steamapps\common\Among Us"
0.45 - GOG: Found game Horizon Zero Dawn™ Complete Edition (1209025141) at "D:\Games\Horizon Zero Dawn"
0.45 - GOG: Found game Ghostrunner (1957528513) at "D:\Games\Bladerunner\Ghostrunner"
0.45 - GOG: Found game Ghostrunner pre-order KATANA DLC (2009792833) at "D:\Games\Bladerunner\Ghostrunner"
0.45 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.52 - EpicGamesStore: Found game Carpathian Mountains at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game Assassin's Creed: Valhalla at "D:\Games\AssassinsCreedValhalla"
0.52 - EpicGamesStore: Found game Chongquing at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game Dubai at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game HITMAN 3 at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game Berlin at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game HITMAN 1 GOTY Upgrade at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game Dartmoor at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game HITMAN 2 Standard at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game HITMAN 1 Complete First Season at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game Mendoza at "D:\Games\HITMAN3"
0.52 - EpicGamesStore: Found game Fortnite at "D:\Games\Fortnite"
0.52 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.76 - Wabbajack Version: 2.5.3.7
1.33 - Build server is alive
1.33 - File hash check (-42) ef23df9f6f37d888b44ce680f85c20f70ef97e58ea180fc1f496660c1efdb66c
1.35 - Build server is alive
1.35 - File hash check (-42) ef23df9f6f37d888b44ce680f85c20f70ef97e58ea180fc1f496660c1efdb66c
3.6 - Loading ModLists from GitHub
4.16 - Error downloading modlist image Relics of Hyrule - GAT Edition
4.16 - Error downloading modlist image Relics of Hyrule - GAT Edition
4.17 - Error downloading modlist image OME(FT)
5.04 - Error downloading modlist image OME(FT)
30.09 - Starting to install Elysium Remastered
30.1 - Cleaning VFS, this may take a bit of time
30.12 - Starting Installer Task
30.13 - Installation has Started
30.13 - File hash check (-42) ef23df9f6f37d888b44ce680f85c20f70ef97e58ea180fc1f496660c1efdb66c
30.33 - Configuring Processor
30.34 - Install Folder: D:\Games\Skyrim Elysium Remastered
30.34 - Downloads Folder: D:\Games\Skyrim Elysium Remastered\downloads
30.34 - Game Folder: D:\Programs\Steam\steamapps\common\Skyrim Special Edition
30.34 - Wabbajack Folder: D:\Downloads\2.5.3.7
30.34 - Drive watcher is starting. Will warn at 8GB and error at 4GB
30.34 - Starting Drive watcher on D:\ currently 1.2TB free out of 1.8TB
30.34 - Validating Game ESMs
30.35 - Creating Output Folders
30.96 - Optimizing ModList
30.96 - Optimizing ModList directives
32.69 - Looking for files to delete
32.72 - Cleaning empty folders
33.45 - Looking for unmodified files
34.72 - Updating ModList
34.72 - Optimized 218352 directives to 218352 required
34.75 - Hashing Archives
34.75 - Looking for files to hash
34.81 - Found 1756 total files, 1741 matching filesize
35.06 - Downloading Missing Archives
35.06 - Missing 147 archives
35.06 - Getting Nexus API Key, if a browser appears, please accept
35.44 - Logged into the nexus as DanThew
35.44 - Nexus calls remaining: 8701 daily, 500 hourly
35.58 - Logged into the nexus as DanThew
35.58 - Nexus calls remaining: 8701 daily, 500 hourly
35.58 - Loading server whitelist
35.69 - Loaded permissions for 652 servers and 292 Google Drive files
35.69 - File hash check (-42) ef23df9f6f37d888b44ce680f85c20f70ef97e58ea180fc1f496660c1efdb66c
35.7 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/pIkl3AQD#zDTeVHnPSSRKPzEjj7ZufGyAImOpqBv0ny-7efp6_8c failed validation

I tried to restart wabbajack few times like people on internet told me but it didnt work.
Hope someone finds a fix for this /dont want to throw 150gb down the drain./

**Comment by KrukToKot** [comment]
> Last night I was downloading Elysium Remastered from using wabbajack and there is the full log I got from the instalation
> 
> 0.3 - Wabbajack Build - 9d251cda832b7478c9480345ee829f46e02df999 0.3 - Running in D:\Downloads\2.5.3.7 0.36 - Detected Windows Version: 10.0.19042.0 0.36 - System settings - (31.9GB RAM) (4.8GB Page), Display: 1920 x 1080 (7.9GB VRAM - VideoMemorySizeMb=10240) 0.36 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance. 0.37 - Getting new Wabbajack version list 0.43 - Steam: Found no Regex matches in Steam Config at d:/programs/steam\config\config.vdf 0.44 - Steam: Found game Rogue Legacy 2 (1253920) at "D:\Programs\Steam\steamapps\common\Rogue Legacy 2" 0.44 - Steam: Found game Goose Goose Duck (1568590) at "D:\Programs\Steam\steamapps\common\Goose Goose Duck" 0.44 - Steam: Found game Lost Ark (1599340) at "D:\Programs\Steam\steamapps\common\Lost Ark" 0.44 - Steam: Found game Steamworks Common Redistributables (228980) at "D:\Programs\Steam\steamapps\common\Steamworks Shared" 0.44 - Steam: Found game Unturned (304930) at "D:\Programs\Steam\steamapps\common\Unturned" 0.44 - Steam: Found game Geometry Dash (322170) at "D:\Programs\Steam\steamapps\common\Geometry Dash" 0.44 - Steam: Found game Wallpaper Engine (431960) at "D:\Programs\Steam\steamapps\common\wallpaper_engine" 0.44 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\Programs\Steam\steamapps\common\Skyrim Special Edition" 0.44 - Steam: Found game Counter-Strike: Global Offensive (730) at "D:\Programs\Steam\steamapps\common\Counter-Strike Global Offensive" 0.44 - Steam: Found game Among Us (945360) at "D:\Programs\Steam\steamapps\common\Among Us" 0.44 - Steam: Found game Rogue Legacy 2 (1253920) at "d:/programs/steam\steamapps\common\Rogue Legacy 2" 0.44 - Steam: Found game Goose Goose Duck (1568590) at "d:/programs/steam\steamapps\common\Goose Goose Duck" 0.44 - Steam: Found game Lost Ark (1599340) at "d:/programs/steam\steamapps\common\Lost Ark" 0.45 - Steam: Found game Steamworks Common Redistributables (228980) at "d:/programs/steam\steamapps\common\Steamworks Shared" 0.45 - Steam: Found game Unturned (304930) at "d:/programs/steam\steamapps\common\Unturned" 0.45 - Steam: Found game Geometry Dash (322170) at "d:/programs/steam\steamapps\common\Geometry Dash" 0.45 - Steam: Found game Wallpaper Engine (431960) at "d:/programs/steam\steamapps\common\wallpaper_engine" 0.45 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "d:/programs/steam\steamapps\common\Skyrim Special Edition" 0.45 - Steam: Found game Counter-Strike: Global Offensive (730) at "d:/programs/steam\steamapps\common\Counter-Strike Global Offensive" 0.45 - Steam: Found game Among Us (945360) at "d:/programs/steam\steamapps\common\Among Us" 0.45 - GOG: Found game Horizon Zero Dawn™ Complete Edition (1209025141) at "D:\Games\Horizon Zero Dawn" 0.45 - GOG: Found game Ghostrunner (1957528513) at "D:\Games\Bladerunner\Ghostrunner" 0.45 - GOG: Found game Ghostrunner pre-order KATANA DLC (2009792833) at "D:\Games\Bladerunner\Ghostrunner" 0.45 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net 0.52 - EpicGamesStore: Found game Carpathian Mountains at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game Assassin's Creed: Valhalla at "D:\Games\AssassinsCreedValhalla" 0.52 - EpicGamesStore: Found game Chongquing at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game Dubai at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game HITMAN 3 at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game Berlin at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game HITMAN 1 GOTY Upgrade at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game Dartmoor at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game HITMAN 2 Standard at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game HITMAN 1 Complete First Season at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game Mendoza at "D:\Games\HITMAN3" 0.52 - EpicGamesStore: Found game Fortnite at "D:\Games\Fortnite" 0.52 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist 0.76 - Wabbajack Version: 2.5.3.7 1.33 - Build server is alive 1.33 - File hash check (-42) ef23df9f6f37d888b44ce680f85c20f70ef97e58ea180fc1f496660c1efdb66c 1.35 - Build server is alive 1.35 - File hash check (-42) ef23df9f6f37d888b44ce680f85c20f70ef97e58ea180fc1f496660c1efdb66c 3.6 - Loading ModLists from GitHub 4.16 - Error downloading modlist image Relics of Hyrule - GAT Edition 4.16 - Error downloading modlist image Relics of Hyrule - GAT Edition 4.17 - Error downloading modlist image OME(FT) 5.04 - Error downloading modlist image OME(FT) 30.09 - Starting to install Elysium Remastered 30.1 - Cleaning VFS, this may take a bit of time 30.12 - Starting Installer Task 30.13 - Installation has Started 30.13 - File hash check (-42) ef23df9f6f37d888b44ce680f85c20f70ef97e58ea180fc1f496660c1efdb66c 30.33 - Configuring Processor 30.34 - Install Folder: D:\Games\Skyrim Elysium Remastered 30.34 - Downloads Folder: D:\Games\Skyrim Elysium Remastered\downloads 30.34 - Game Folder: D:\Programs\Steam\steamapps\common\Skyrim Special Edition 30.34 - Wabbajack Folder: D:\Downloads\2.5.3.7 30.34 - Drive watcher is starting. Will warn at 8GB and error at 4GB 30.34 - Starting Drive watcher on D:\ currently 1.2TB free out of 1.8TB 30.34 - Validating Game ESMs 30.35 - Creating Output Folders 30.96 - Optimizing ModList 30.96 - Optimizing ModList directives 32.69 - Looking for files to delete 32.72 - Cleaning empty folders 33.45 - Looking for unmodified files 34.72 - Updating ModList 34.72 - Optimized 218352 directives to 218352 required 34.75 - Hashing Archives 34.75 - Looking for files to hash 34.81 - Found 1756 total files, 1741 matching filesize 35.06 - Downloading Missing Archives 35.06 - Missing 147 archives 35.06 - Getting Nexus API Key, if a browser appears, please accept 35.44 - Logged into the nexus as DanThew 35.44 - Nexus calls remaining: 8701 daily, 500 hourly 35.58 - Logged into the nexus as DanThew 35.58 - Nexus calls remaining: 8701 daily, 500 hourly 35.58 - Loading server whitelist 35.69 - Loaded permissions for 652 servers and 292 Google Drive files 35.69 - File hash check (-42) ef23df9f6f37d888b44ce680f85c20f70ef97e58ea180fc1f496660c1efdb66c 35.7 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/pIkl3AQD#zDTeVHnPSSRKPzEjj7ZufGyAImOpqBv0ny-7efp6_8c failed validation
> 
> I tried to restart wabbajack few times like people on internet told me but it didnt work. Hope someone finds a fix for this /dont want to throw 150gb down the drain./

i also have this issue
