### ISSUE TITLE
Attempt to disable Movement Behavior Overhaul SE

### ISSUE THREAD

**Issue by TaylorJay47** [TitansBane/Elysium-Remastered#44]
I'm having a lot of fun playing, but I usually play Skyrim in first person and as it stands now the jarring animations make it near impossible to play in first person. I'm not sure if I'm missing something here, or if I just need to set something differently, but when I try to disable Movement Behavior Overhaul SE, all characters just T-pose.

After a bit of research, The consensus seemed to just be to run Nemesis again and it should fix the t-poses, but not only would Nemesis not update or run, but it wouldn't find MBO in the first place. If I can fix the jarring first person animations without disabling MBO, that would be preferred since I figured it adds to the experience.

Again, I'm completely understanding if it's just me being dumb here, but I figured I'd reach out just in case anyone else is seeing this same thing.

**Comment by clausagerskov** [comment]
https://github.com/TitansBane/Elysium/issues/141
