### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by MortishaLarsen** [TitansBane/Elysium-Remastered#5]
Error "Unable to download Elysium Remastered - Dyndolod 3d Output 7z (WabbajackCDNDownloader+State } https://authored-files.wabbajack.org/Elysium Remastered - Dyndolod 3D Output.7z_b960788c-b960788c-6024-45bc-ba3d-d81623219e76_

**Comment by rednexuz** [comment]
I'm continually having the same problem, even though I tried to download the files from a mega.co link someone offered in response to this problem - but they were for the regular Elysium dyndolod files. I've deleted the files in question (and the modlist files), and tried to redownload, but still getting the same problem.  I'm including a screenshot of my log file 
![image](https://user-images.githubusercontent.com/100396459/155649548-7ea322d1-8c68-4278-8628-c2d571490276.png)

**Comment by TitansBane** [comment]
You'll get better help on the Wabbajack discord as this mainly pertains to actual issues with the list itself.
