### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AzrealMarkieve** [TitansBane/Elysium-Remastered#6]
I've reinstalled the modlist 6 times now. Followed the instructions to the letter. Within 10 minutes of loading into a game it crashes during loading screens. Consistently. 

I have an 
RTX 2060 Super,
Intel i5-9600k 3.70GHz,
16 GB of RAM,

I don't know if I'm missing something, but with a clean install of Skyrim and doing literally everything in the Readme, running the game without anything else running, the consistent crashes on loading screens are making it unplayable.

**Comment by TitansBane** [comment]
Most likely a memory crash, so you'll need to increase your pagefile.

**Comment by AzrealMarkieve** [comment]
Well, I increased my pagefile and it definitely helped. I played for two hours and didn't have a crash on any loading screens.
