### ISSUE TITLE
Installation via Wabbajack stops at: (8/22) Downloading missing archives

### ISSUE THREAD

**Issue by ghost** [TitansBane/Elysium-Remastered#66]
Log is attached. I extracted the error below. Thank you very much in advance.

30,24 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/5IUHBISY#TRq5anNoYJ3ZqWhvI1A8emlbgkJsG6a9iOXy2VpI9_I failed validatio
[Wabbajack.current.log](https://github.com/TitansBane/Elysium-Remastered/files/9167941/Wabbajack.current.log)

**Comment by 0ddoblivion** [comment]
Just came here to say I have the same issue today.

**Comment by Exii-iv** [comment]
discord seems to say there’s an incoming update coming and to wait for that (core files not up etc.)

**Comment by Iyumon** [comment]
I have the same issue.

**Comment by Exii-iv** [comment]
STATUS: this version of the mod list is technically unavailable atm due to this mega file. an update is on the way, it's just a matter of waiting for it. you can find all the info you need on the Elysium/Aldnari discord

**Comment by MythicMos** [comment]
As of today, (Aug 21, 2022) Launcher again failed to validate files.
77.65 - Encountered error, can't continue - System.Exception: File MegaDownloader+State|https://mega.nz/file/UUcGhJrK#5kdWojs6_CUy5BttFEsv_TUcAwbuShhtJitTcTjy1TI failed validation
   at Wabbajack.Lib.AInstaller.DownloadArchives() in c:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 226
