### ISSUE TITLE
Elysium Remastered - Dyndolod 3D Output.7z is failing to hash. 

### ISSUE THREAD

**Issue by TheClock69** [TitansBane/Elysium-Remastered#7]
Hi there,

Today, I have had a consistent issue with downloading the repository stated in the title. I am guessing this will be sorted in time, however I thought it worth mentioning, to potentially get it sorted, sooner.

The file/data will download - the progress bar will get all the way to the end in the next step, when hashing - and then I get a download failed notice.

Any support would be appreciated. I did try to download Elysium - Dyndolod 3D Output.7z from MEGA, but this, of course, is an old copy (I wondered if renaming it would help). I have also noticed the 'Elysium Remastered - Dyndolod 3D Output.7z' is in the downloads file at a respectable size of 5.51GB, as expected. It is strange to me that it would fail to hash. But, then again, I am still yet to even learn what 'hashing' is!

Thanks for your help.

I have enjoyed Skyrim Elysium in the past - and I am most excited to get on with it again, revamped!

All the best in life,

Jay/ TheClock69.

[Wabbajack 2022-02-28 17_07_48.log](https://github.com/TitansBane/Elysium-Remastered/files/8157676/Wabbajack.2022-02-28.17_07_48.log)
[Wabbajack 2022-02-28 18_12_57.log](https://github.com/TitansBane/Elysium-Remastered/files/8157677/Wabbajack.2022-02-28.18_12_57.log)
[Wabbajack 2022-02-28 22_21_28.log](https://github.com/TitansBane/Elysium-Remastered/files/8157678/Wabbajack.2022-02-28.22_21_28.log)
[Wabbajack.current.log](https://github.com/TitansBane/Elysium-Remastered/files/8157679/Wabbajack.current.log)

**Comment by TheClock69** [comment]
To correct and clarify myself, I receive an 'Installation Failed' notice
![Installation_Failed](https://user-images.githubusercontent.com/100643499/156077886-0ae3933a-5faa-4a77-89f5-d8e2705622c4.png)
.

**Comment by GregorWenzel** [comment]
I'm having the same issue...

**Comment by TheClock69** [comment]
> I'm having the same issue...

I have decided to buy and mod the witcher 3 with the first person mod - and various quality of life mods, to pass the time! 
Just saying, it may be a nice recommendation.

;)

**Comment by rperezandreiuk** [comment]
Same here, friend.
I cannot download Elwaps, Core files and Dyndolod. 
Well... let´s hope for the best to happen soon.
Thanks!

**Comment by TheClock69** [comment]
The discord server (wabbajack -> Elysium (remastered), did provide some support. Individual support, as well so big thumbs up. But, I am still unavailable to download, even after deleting everything, and starting again. Trying again, this morning. It seems like there has been an update. All the best!

**Comment by TheClock69** [comment]
So, today I deleted everything and restarted (Everything, being skyrim, all of the mods from WJ) (Restarted being, reinstalling Skyrim, reinstalling Creation club content, WJ install), and it seemed to have worked! So, this is my suggestion - delete all of the related content - and start a fresh! I wonder why it had failed, but perhaps WJ got snagged on some pre-existing content. Guilty!

all the best, and good luck!
