### ISSUE TITLE
Mod organizer press run not working

### ISSUE THREAD

**Issue by Ghitubuser** [TitansBane/Elysium-Remastered#81]
I checked that all the versions matched, skse runs with no mods activated but when they are then there is a flicker of the screen which then dissapears. Skyrim in task manager is a background process. I tried from the other post but all my antivirus is turned off

**Comment by okkonaut** [comment]
Some problem here . Trying to start skyrim from mo2 but it only opens a cmd window for 1 second and then crashes. Does anyone got a solution? Would be awesome

**Comment by Coalier** [comment]
Did yall ever figure it out cause I have the same Issue
