### ISSUE TITLE
Stuck at first loading screen

### ISSUE THREAD

**Issue by Wra666** [TitansBane/Elysium-Remastered#82]
![image](https://user-images.githubusercontent.com/107369699/196305132-5af3f319-37b5-430c-9312-e11eab6e1330.png)
![image](https://user-images.githubusercontent.com/107369699/196305155-a8558798-0b9c-499b-9600-6d9adb3ec3e8.png)

Stuck loading even tho task manager says not responding

**Comment by heartexho** [comment]
Does anybody have a clue how to fix it? I don't even have an option to disable vsync in enblocal.ini, I tried adding it manually, but no difference.

**Comment by ItsRogueRen** [comment]
Why was this marked as completed? Was there a solution? I'm having this happen and this was the only issue about it but there is nothing else here
