### ISSUE TITLE
Crash after MO2

### ISSUE THREAD

**Issue by MisterXx21** [TitansBane/Elysium-Remastered#83]
Hi everyone,
After I press start in MO2 a black screen come and then a blue skill tree loading screen. But after 7 sec. it will be crash.
[Crash_2022_10_22_21-31-6.txt](https://github.com/TitansBane/Elysium-Remastered/files/9845150/Crash_2022_10_22_21-31-6.txt)

**Comment by TheOneLiliad** [comment]
Omg I get the exact same crash!!!!!
