### ISSUE TITLE
Unable to download Synthesis.zip 

### ISSUE THREAD

**Issue by Klemeshov** [TitansBane/Elysium-Remastered#86]
############ Wabbajack log file - 2022-11-01 00:02:28.9131 ############
00:00:00.000 [ERROR] (Wabbajack.Downloaders.GameFile.GameLocator) GOG was not found in the registry
00:00:00.022 [INFO] (Wabbajack.Downloaders.GameFile.GameLocator) Found no Ids and Paths in the MFST files
00:00:00.299 [INFO] (Wabbajack.MainWindowVM) App Location: 
00:00:00.299 [INFO] (Wabbajack.MainWindowVM) Wabbajack Version: 3.0.3.1
00:00:00.396 [INFO] (Wabbajack.MainWindow) Wabbajack Build - 7b72c529a936ab7cac30382f02dc3f6d6d59db76
00:00:00.396 [INFO] (Wabbajack.MainWindow) Running in D:\Wabbajack\3.0.3.1
00:00:00.424 [INFO] (Wabbajack.MainWindow) Detected Windows Version: Microsoft Windows NT 10.0.22000.0
00:00:00.424 [INFO] (Wabbajack.MainWindow) System settings - (31,8GB RAM) (4,8GB Page), Display: 2560 x 1440 (23,8GB VRAM - VideoMemorySizeMb=10240)
00:00:00.424 [INFO] (Wabbajack.MainWindow) Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance
00:00:00.435 [INFO] (Wabbajack.LauncherUpdater) Getting new Wabbajack version list
00:00:05.852 [INFO] (Wabbajack.InstallerVM) Preparing HttpDownloader
00:00:05.852 [INFO] (Wabbajack.InstallerVM) Preparing GameFileDownloader
00:00:05.852 [INFO] (Wabbajack.InstallerVM) Preparing NexusDownloader
00:00:05.852 [INFO] (Wabbajack.InstallerVM) Preparing MegaDownloader
00:00:06.110 [INFO] (Wabbajack.InstallerVM) Preparing WabbajackCDNDownloader
00:00:06.110 [INFO] (Wabbajack.InstallerVM) Preparing GoogleDriveDownloader
00:00:06.126 [INFO] (Wabbajack.Installer.StandardInstaller) Installing: Elysium Remastered - 0.0.1.0
00:00:06.314 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Configuring Installer
00:00:06.314 [INFO] (Wabbajack.Installer.StandardInstaller) Configuring Processor
00:00:06.314 [INFO] (Wabbajack.Installer.StandardInstaller) Install Folder: D:\Elysium
00:00:06.314 [INFO] (Wabbajack.Installer.StandardInstaller) Downloads Folder: D:\Elysium\downloads
00:00:06.314 [INFO] (Wabbajack.Installer.StandardInstaller) Game Folder: D:\SteamLibrary\steamapps\common\Skyrim Special Edition
00:00:06.314 [INFO] (Wabbajack.Installer.StandardInstaller) Wabbajack Folder: D:\Wabbajack\3.0.3.1
00:00:06.314 [INFO] (Wabbajack.Installer.StandardInstaller) Optimizing ModList directives
00:00:07.438 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for files to delete
00:00:07.451 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Cleaning empty folders
00:00:07.893 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Looking for unmodified files
00:00:07.983 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Updating ModList
00:00:07.983 [INFO] (Wabbajack.Installer.StandardInstaller) Optimized 301888 directives to 301888 required
00:00:08.022 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:08.022 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:08.026 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:08.026 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:08.026 [INFO] (Wabbajack.Installer.StandardInstaller) Found 2390 total files, 2302 matching filesize
00:00:08.147 [INFO] (Wabbajack.Installer.StandardInstaller) Missing 1 archives
00:00:08.147 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading validation data
00:00:08.322 [INFO] (Wabbajack.Installer.StandardInstaller) Validating Archives
00:00:08.322 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading missing archives
00:00:08.322 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading 1 archives
00:00:08.322 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Downloading files
00:00:08.322 [INFO] (Wabbajack.Installer.StandardInstaller) Downloading Synthesis.zip
00:00:32.045 [FATAL] (Wabbajack.Downloaders.DownloadDispatcher) While finding mirror for jrZN4JTc3Tw=|System.NullReferenceException: Object reference not set to an instance of an object.
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 83
   at Wabbajack.Downloaders.WabbajackCDNDownloader.Download(Archive archive, WabbajackCDN state, AbsolutePath destination, IJob job, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.WabbajackCDN\WabbajackCDNDownloader.cs:line 121
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, Job`1 job, CancellationToken token, Nullable`1 useProxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 102
   at Wabbajack.Downloaders.DownloadDispatcher.Download(Archive a, AbsolutePath dest, CancellationToken token, Nullable`1 proxy) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 48
   at Wabbajack.Downloaders.DownloadDispatcher.DownloadFromMirror(Archive archive, AbsolutePath destination, CancellationToken token) in c:\oss\wabbajack\Wabbajack.Downloaders.Dispatcher\DownloadDispatcher.cs:line 219
00:00:32.045 [ERROR] (Wabbajack.Installer.StandardInstaller) Downloaded hash AAAAAAAAAAA= does not match expected hash: jrZN4JTc3Tw=
00:00:32.045 [INFO] (Wabbajack.Installer.StandardInstaller) Next Step: Hashing Archives
00:00:32.045 [INFO] (Wabbajack.Installer.StandardInstaller) Looking for files to hash
00:00:32.045 [INFO] (Wabbajack.Installer.StandardInstaller) Getting archive sizes
00:00:32.045 [INFO] (Wabbajack.Installer.StandardInstaller) Linking archives to downloads
00:00:32.057 [INFO] (Wabbajack.Installer.StandardInstaller) Found 2390 total files, 2302 matching filesize
00:00:32.137 [FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Synthesis.zip (HTTPDownloader+State|https://github.com/Mutagen-Modding/Synthesis/releases/download/0.24.1/Synthesis.zip)
00:00:32.137 [FATAL] (Wabbajack.Installer.StandardInstaller) Cannot continue, was unable to download one or more archives

**Comment by arthurdemarchi** [comment]
I was facing the same problem last week, today i've changed the download folder path to be inside the instalation folder (It's actually the default path of wabbajack). I don't if this has something to do with it, or if somehting got fixed during the week. But the error is now gonne.

**Comment by Zelekana** [comment]
I used the MEGA link sent by Foxman on the Discord server to manual download the Synthesis.zip, put it into the download folder, and then restarted WJ and it worked for me! 

https://mega.nz/file/kAlmRKZC#1LLx59KfpE5C7QG57HW6_10wy-hbS-lEywdbPZ48m_4

**Comment by Klemeshov** [comment]
the mega link solved the problem, thx
