### ISSUE TITLE
not able to download 1 file Synthesis zip ?? 

### ISSUE THREAD

**Issue by cj31781** [TitansBane/Elysium-Remastered#89]
[FATAL] (Wabbajack.Installer.StandardInstaller) Unable to download Synthesis.zip (HTTPDownloader+State|https://github.com/Mutagen-Modding/Synthesis/releases/download/0.24.1/Synthesis.zip)

does anyone have this issue or know a work around ? or do i  just need to wait for a new updated version of this file to be made .. all other files download except this one ??

**Comment by Zelekana** [comment]
I used the MEGA link sent by Foxman on the Discord server to manual download the Synthesis.zip, put it into the download folder, and then restarted WJ and it worked for me! 

https://mega.nz/file/kAlmRKZC#1LLx59KfpE5C7QG57HW6_10wy-hbS-lEywdbPZ48m_4

**Comment by cj31781** [comment]
Zelekana your a legend just downloaded from link and working perfect.. anyone else get this issue then follow link above

**Comment by oliveirarafa** [comment]
It worked for me too.

**Comment by WretchedAbyss** [comment]
Thanks, had the same issue. The Mega download works.

**Comment by cameronmbell99** [comment]
Had the same issue, and using the Mega Download worked for me too.
