### ISSUE TITLE
The game crashes when I drink a potion that I made myself

### ISSUE THREAD

**Issue by Klemeshov** [TitansBane/Elysium-Remastered#90]
If you make potions with 2 effects (positive and negative) and drink, the game crashes, in my case it is the effect of invisibility and poison or the effect of restoring health and paralysis or fear

**Comment by arimammela** [comment]
I have similar problem, but for me it crashes every time I use any kind of potion considered poison.

**Comment by TitansBane** [comment]
The problem is fixed for the next update. However, you can fix it by either disabling the Yes Im Sure mod or switching to the older version right here. https://www.nexusmods.com/skyrimspecialedition/mods/24898?tab=files&file_id=126540
