### ISSUE TITLE
GOG Skyrim SE/AE Support

### ISSUE THREAD

**Issue by n3IVI0** [TitansBane/Elysium-Remastered#91]
Will your epic Elysium Remastered modlist have GOG support when WJ finally fully supports this version? Thank you.

**Comment by xze20** [comment]
Would really like to see this too, and Wabbajack currently supports GOG Skyrim SE/AE as of 3.0.4.0 -> https://github.com/wabbajack-tools/wabbajack/releases/tag/3.0.4.0


<img width="701" alt="Screenshot 2022-11-18 050838" src="https://user-images.githubusercontent.com/118535072/202702047-07a7b190-f97d-4e28-b813-90eb670606c7.png">

**Comment by TitansBane** [comment]
Many mods in the list don't support GOG yet. So no plans for GOG support atm.
