### ISSUE TITLE
UpscalerBasePlugin-491-1-0-4-1671213395 has been removed from nexus

### ISSUE THREAD

**Issue by thefrenchflo** [TitansBane/Elysium-Remastered#94]
And so it's not possible anymore to install Elysium from Wabbajack.

**Comment by TheNaSMaX** [comment]
Same here

**Comment by Risdiz** [comment]
the thing was taken down because of copyright from nvidea (some dlls)

**Comment by TheNaSMaX** [comment]
well damn, so does this make the whole damn thing null? Can we...bypass it? First time using wabbajack...

**Comment by Risdiz** [comment]
wait for an update (look on their discord for the announcement)
