### ISSUE TITLE
CTD on opening world map in certain locations

### ISSUE THREAD

**Issue by Emraldsoul** [TitansBane/Elysium-Remastered#96]
Hi I've been trying to diagnose this CTD issue i have with my Elysium install but i cannot figure out how to deal with this. Please help

[Crash_2023_1_3_20-16-46.txt](https://github.com/TitansBane/Elysium-Remastered/files/10339265/Crash_2023_1_3_20-16-46.txt)
[Crash_2023_1_3_20-22-28.txt](https://github.com/TitansBane/Elysium-Remastered/files/10339266/Crash_2023_1_3_20-22-28.txt)

Here are 2 files when opening the word map in the town winterhold. the communality in the crash logs i keep seeing is:
  [   0]    TESFurniture(Name: `Anvil`, FormId: 0001A2AD, File: `Skyrim.esm`)
  [   0]    TESObjectREFR(FormId: 430089C2, File: `Cities & Towns Patches Merge.esp <- JKs Skyrim.esp`, BaseForm: TESFurniture(Name: `Anvil`, FormId: 0001A2AD, File: `Skyrim.esm`))

On the first two lines. 
Its always somthing like Anvil or Bedroll in skyrim.esm
And has to do with Cities & Towns Patches Merge.esp

I have tried to disable Cities & Towns Patches Merge.esp in MO2 but then it results in and CTD on startup like the log bellow

[Crash_2023_1_3_20-22-28.txt](https://github.com/TitansBane/Elysium-Remastered/files/10339300/Crash_2023_1_3_20-22-28.txt)

I'm not that good at reading the logs and don't know how to resolve this.
Any help would be greatly appreciated!!

Kind regards,
Rob

**Comment by TitansBane** [comment]
I can't replicate such crashes. I suggest not adding mods like HDT, etc., and you won't have these CTDs.

**Comment by Emraldsoul** [comment]
Hi, i have a completely new install of skyrim and Elysium still same CTD issue's can sombody please help me or should i go elsewhere for help?

This happens in  Morthal
[Crash_2023_1_5_23-30-48.txt](https://github.com/TitansBane/Elysium-Remastered/files/10356163/Crash_2023_1_5_23-30-48.txt)

This happens in Riverwood
[Crash_2023_1_5_23-35-34.txt](https://github.com/TitansBane/Elysium-Remastered/files/10356167/Crash_2023_1_5_23-35-34.txt)

Same issue ass mentioned in my previous post.

And again, any help would be greatly appreciated!!
