### ISSUE TITLE
Can't start up game in mo2

### ISSUE THREAD

**Issue by Zahii00** [TitansBane/Elysium-Remastered#97]
Hello- I followed every step during installation process and end up with this, what can I do to play?
![Zrzut ekranu 2023-01-04 143934](https://user-images.githubusercontent.com/121951746/210568135-dc3ebc55-764a-40a3-833d-033eccd936e7.png)
![Zrzut ekranu 2023-01-04 143953](https://user-images.githubusercontent.com/121951746/210568140-de884bd0-4b5e-4ff0-b4f6-26416cbeb915.png)
![Zrzut ekranu 2023-01-04 144327](https://user-images.githubusercontent.com/121951746/210568142-207e74d0-24cc-498b-a97b-a911560bba6c.png)

**Comment by Zahii00** [comment]
Okay after few tries it started. But crashes during the new save startup

**Comment by Zahii00** [comment]
It says the game wasn't fully loaded- what can i do to fully load it?

**Comment by TitansBane** [comment]
These errors should be fixed with the latest silent update.
