### ISSUE TITLE
Stuck on the Quest The Way of the Voice

### ISSUE THREAD

**Issue by NbClKaiZer** [TitansBane/Elysium-Remastered#98]
In my current playthrough im hardstuck on the Way of the Voice. I was able to shout at Master Arengeir, and I was able to learn the second part of the shout from the runes appearing on the floor. But after that, no new quest marker appears. Einhar doesn't let me "tap into his understanding". He compltetely ignores me. I've tried a couple of things recommended from years ago when this quest was seemingly bugged in the base game, nothing worked. Using the console to progress the quest works somewhat - I can learn the shout and progress, have to use the console again to learn the next shout out in the yard and so on. However, by doing this, once the Way of the Voice is finished and Arengeir sends me to find the Horn of Jurgen Windcaller, the respective quest doesn't trigger. No entry in the quest book, no quest marker, nothing.

**Comment by TitansBane** [comment]
This has already been fix.

**Comment by jirimakarius** [comment]
Same thing happened to me.

Running version v2.7.0
